### ISSUE TITLE
Add Timeline Component

### ISSUE THREAD

**Issue by VulpesVulpes825** [UW-FLOM/flom-react#67]
Implement a tileline component using React Hooks with following parameters:

- `events` parameter that will take an array of events. The array's item will be an array containing three values:
  - `status` parameter indicating the event status, such as `success`, `pending`, `error`.
  - `label` parameter that accept a string explaning what the event is.
 
[Antd Timeline Component](https://ant.design/components/timeline/) is a good example.

**Comment by ctuguinay** [comment]
I'm a bit confused on how I should test my timeline component. Should I just call it from one of the component pages like home page? If so, I'm unsure of why nothing is changing on localhost:3000. I even tried changing the sample text text on home page to some other text, but still no changes were seen. After my changes were placed, I ran yarn dev:setup in the project containers. I even did this again but closed and reopened localhost:3000 and still no changes were seen. I'm unsure of how to go about this.

**Comment by VulpesVulpes825** [comment]
@ctuguinay 

> Should I just call it from one of the component pages like home page?
Yes, please do so.
> I'm unsure of why nothing is changing on localhost:3000.
If you add a file that does not exist before initializing docker containers, it seems docker will not load the new file. In this case, destroy the docker containers using `yarn dev:destroy` and then `yarn dev:start`(It will be quick if you did not change package.json). You can ssh to the container now to see if the file is loaded or not.

**Comment by VulpesVulpes825** [comment]
@ctuguinay If running the previous two command did not solve the issue, consider `yarn dev:destroy` and then  `docker system prune -a --volumes`.

**Comment by MK-WiD** [comment]
What need is this solving?
