### ISSUE TITLE
Allow Adding and Editing Survey json in dashboard

### ISSUE THREAD

**Issue by VulpesVulpes825** [UW-FLOM/flom-react#81]
## Dashboard
- [ ] Use [react-codemirror2](https://github.com/scniro/react-codemirror2) for an JSON editor
- [ ] Verify JSON before submitting
## API
- [x] Have an api entry `POST /api/user/survey`

**Comment by MK-WiD** [comment]
AddSurvey page added. No survey Edit will be allowed to preserve survey integrity and results.
